---
- name: Download do WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extracting the wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/usr/share/nginx/html/ copy=no
 
- name: Template archive wp-config
  template:
     src: wp-config.php.j2
     dest: /usr/share/nginx/html/wp-config.php
  notify: restart nginx